#!/usr/bin/env python3
"""Generate Obsidian daily note from news-data.json"""

import json
from datetime import datetime

with open('data/news-data.json', 'r') as f:
    data = json.load(f)

major = [n for n in data['news'] if n.get('stars', 0) >= 4][:10]
watched = [n for n in data['news'] if n.get('watched')][:5]

today = datetime.now().strftime('%Y-%m-%d %A')
lines = []
lines.append(f'# {today} 每日要闻简报')
lines.append('')
lines.append(f'**总计 {data["total_count"]} 条 | >=4 star major {data["major_count"]}条 | keyword hit {data["watched_count"]}条**')
lines.append('')

if major:
    lines.append('## Major Events')
    lines.append('')
    for i, n in enumerate(major, 1):
        lines.append(f'{i}. **[{n.get("stars",0)} star] [{n.get("category","")}]** {n.get("title","")}')
        lines.append(f'   > {n.get("summary","")}')
        lines.append('')

if watched:
    lines.append(f'## Keyword Hits ({len(watched)})')
    lines.append('')
    for n in watched:
        lines.append(f'- **{n.get("title","")}** ({n.get("source","")})')
    lines.append('')

lines.append(f'---')
lines.append(f'*Generated by NewsPulse | {data.get("fetched_at","")} | sources: {data.get("sources_used",0)} RSS*')

with open('obsidian-daily.md', 'w') as f:
    f.write('\n'.join(lines))

print('Daily note generated')
